# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 200)
        MainWindow.setMinimumSize(QtCore.QSize(320, 200))
        MainWindow.setMaximumSize(QtCore.QSize(320, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(79, 30, 221, 30))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(79, 70, 221, 30))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(10, 130, 150, 30))
        self.loginButton.setObjectName("loginButton")
        self.label_user = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(10, 30, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.label_pass = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(10, 70, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_pass.setFont(font)
        self.label_pass.setObjectName("label_pass")
        self.signupButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signupButton.setGeometry(QtCore.QRect(160, 130, 150, 30))
        self.signupButton.setObjectName("signupButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.label_user.setText(_translate("MainWindow", "Username:"))
        self.label_pass.setText(_translate("MainWindow", "Password:"))
        self.signupButton.setText(_translate("MainWindow", "Signup"))
