# Form implementation generated from reading ui file 'user_signup.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.firstNameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.verticalLayout.addWidget(self.firstNameLineEdit)
        self.lastNameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.verticalLayout.addWidget(self.lastNameLineEdit)
        self.userNameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.verticalLayout.addWidget(self.userNameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.dobDateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dobDateEdit.setCalendarPopup(True)
        self.dobDateEdit.setObjectName("dobDateEdit")
        self.verticalLayout.addWidget(self.dobDateEdit)
        self.objectiveTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.objectiveTextEdit.setObjectName("objectiveTextEdit")
        self.verticalLayout.addWidget(self.objectiveTextEdit)
        self.signupButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signupButton.setObjectName("signupButton")
        self.verticalLayout.addWidget(self.signupButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signup"))
        self.firstNameLineEdit.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.lastNameLineEdit.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.userNameLineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.objectiveTextEdit.setPlaceholderText(_translate("MainWindow", "Objective"))
        self.signupButton.setText(_translate("MainWindow", "Sign Up"))
